apiVersion: v1
kind: ConfigMap
metadata:
  name: peer-parms
  namespace: trident
data:
  parms.json: |
    {
        "source": {
            "fsID": "<source-fsxn-fsid>",
            "svmName": "<source-svm-name>",
            "secretId": "<source-aws-secret-manager-id>",
        }, 
        "destenation":{
            "fsID": "<destenation-fsxn-fsid>",
            "svmName": "<destenation-svm-name>",
            "secretId": "<destenation-aws-secret-manager-id>",
        },
        "cleanup": true,
        "create": true,
        "region": "<aws-region>"
    }